### ISSUE TITLE
Avoiding boolean solution is too complex.

### ISSUE THREAD

**Issue by robinclart** [guzzilar/code-standard-php#1]
> 14. Avoid using boolean as one of a parameter.

How about using array as named arguments instead?

```php
$exporter->exportData('report_a', array('includeHeader' => true, 'includeFooter' => false));
```

**Comment by guzzilar** [comment]
@robinclart That's also nice too 👍 
I think in some case that way is also make an interface descriptive as well (if they don't create much `if ... else` conditional block inside that function).

Or even we can go with,
```php
$exporter->exportData(
    'report_id',
    Template::include(['header', 'footer'])
);
```

Then exporter doesn't need to take any responsibility about make a template by itself (easy to write test also).

**Comment by guzzilar** [comment]
@robinclart Can I add your idea to the README file? 😁

**Comment by guzzilar** [comment]
Have second thought.
As from the current solution, if I just remove `boolean` from the 2nd and 3rd args from `exportData()` and have method `includeHeader()` and `includeFooter()` instead. Then, in real implementation those 2 methods will do nothing more than.

```php
public function includeHeader()
{
    $this->headerNeeded = true;
}

public function includeFooter()
{
    $this->footerNeeded = true;
}
```

Which is just create another issue instead.

Thanks for pointing it out! @robinclart 
Updated document.
